### ISSUE TITLE
Invoke Celery Task

### ISSUE THREAD

**Issue by mpetyx** [xaralis/django-static-sitemaps#52]
Hello,
I have everything setup and when I run the command 
`python manage.py refresh_sitemap`
I get the desired result.
But my platform is reaaaally big thus it takes several hours to generate the complete sitemap.
I need to have it run as a celery job.
I just haven't managed to make it work.. I have it added on my django apps, I also have celery run on the background, when celery starts the task
`. static_sitemaps.tasks.GenerateSitemap` 
is registered properly. But looking on what celery jobs run, this never goes there..
Sooo... How do I invoke to run on the background?

**Comment by xaralis** [comment]
Hi @mpetyx , thx for trying out the `django-static-sitemaps`. From your description it seems that the celery job is registered, but never being run, is that correct?

Do you have `STATICSITEMAPS_REFRESH_AFTER` set up properly? If your job runs for several hours, it would be good to modify it (see https://github.com/xaralis/django-static-sitemaps#advanced-settings).

Otherwise, I'm not sure where the problem could be, you can refer to https://github.com/xaralis/django-static-sitemaps/blob/master/static_sitemaps/tasks.py . I'm personally no using this package for quite a while now (doing Node.js mostly) so it's possible that the Celery requires tasks to be defined in some other way now. The task definition is really simple so if you manage to update it, a PR would be awesome.

**Comment by mpetyx** [comment]
Hello @xaralis and thanks for responding.
I have this parameter `STATICSITEMAPS_REFRESH_AFTER` already defined but it doesn't seem to work..
It seems like an issue with celery not executing it. I will look deeper at it and PR if something worthy comes up!
